export { default as langDict } from './langDict'
export { default as Register } from './Register'
export { default as CheckoutForm } from './CheckoutForm'
export { default as Setting } from './Setting'
export { default as LoginForm } from './LoginForm'
export { default as RegisterForm } from './RegisterForm'
