export const hiraganaSentense = [
  'しんかんせんにのって、とうきょうからおおさかまでいくことにしました。はじめてのしんかんせんは、とてもはやくて、どきどきしました。でも、きれいなけしきをみながらのんびりとたびをたのしめました。とうきょうやきょうと、おおさかでは、たくさんのおいしいたべものをたべたり、みどころをまわったりしました。せかいはおおきくて、まだまだみたことのないところがたくさんあるので、またいろんなところにいってみたいです。',
  'おおきなのっぽのふるどけい、おじいさんのとけい、ひゃくねんいつもうごいていた、ごじまんのとけいさ、おじいさんのうまれたあさに、かってきたとけいさ、いまはもううごかないそのとけい、ひゃくねんやすまずに、ちくたくちくたく、おじいさんといっしょに、ちくたくちくたく、いまはもううごかない、そのとけい、なんでもしってるふるどけい、おじいさんのとけい、きれいなはなよめやってきた、そのひもうごいてた、うれしいこともかなしいことも、みなしってるとけいさ、いまはもううごかないそのとけい、ひゃくねんやすまずに、ちくたくちくたく、おじいさんといっしょに、ちくたくちくたく、いまはもううごかない、そのとけい',
  'かにのにぎりめしおうばったさるわとうとうかににかたきをとられた。かにはうす、はち、たまごとともに、おんてきのさるをころしたのである。そのはなしはいまさらしないでもよい。たださるをしとめたあと、かにをはじめどうしのものはどういううんめいにほうちゃくしたか、それをはなすことはひつようである。なぜといえばおとぎばなしはぜんぜんこのことははなしていない。いや、はなしていないどころか、あたかもかにはあなのなかに、うすはだいどころのどまのすみに、はちはのきさきのはちのすに、たまごはもみがらのはこのなかに、たいへいぶじなしょうがいでもおくったかのようによそおっている',
  'うさぎおいしかのやま、こぶなつりしかのかわ、ゆめはいまもめぐりて、わすれがたきふるさと、いかにいますちちはは、つつがなしやともがき、あめにかぜにつけても、おもいいずるふるさと、こころざしをはたして、いつのひにかかえらん、やまはあおきふるさと、みずはきよきふるさと',
  'やがてやってくるろうごのために、いまからおかねのじゅんびをはじめることがたいせつです。ろうごにひつようなせいかつひやいりょうひはたかく、ねんきんせいどのげんかいもあるため、じぶんでせっきょくてきにしさんけいせいをしていくことがひつようです。ていきてきなちょきんやとうし、ふどうさんとうし、ろうごにびょうきになったときのためのけんこうほけんなど、ろうごにそなえたほうがよいことはたくさんあります。しかし、いちばんたいせつなのは、いまからむりをせず、ちゃくじつにちょきんをすることです。ろうごにふあんをかんじるかたは、まずはせいかつひさんかげつぶんのちょきんからはじめるとよいでしょう。すこしずつでもこつこつためていけば、あんしんしたろうごをおくることができるはずです。',
]
export const englishSentense = [
  'aaa. bbb.',
  "As the sun slowly dipped below the horizon, casting a warm glow across the sky, I found myself standing at the edge of a vast ocean, its waves crashing against the rocky shore with a rhythmic ebb and flow that lulled me into a peaceful trance, and as I gazed out at the endless expanse of blue, I couldn't help but feel small and insignificant in the face of such natural grandeur, yet at the same time, I felt a profound sense of connectedness to the world around me, as if the ocean and sky were part of me and I a part of them, and I knew in that moment that I would never forget this awe-inspiring display of nature's majesty.",
  "As I strolled through the park on a sunny afternoon, the gentle breeze carried the sound of chirping birds and rustling leaves, while the warm sun rays enveloped my skin with a soothing warmth that put my mind at ease, and I couldn't help but feel grateful for this moment of peace and tranquility amidst the chaos of daily life, as I observed children playing on the playground with joyous laughter, families enjoying picnics on the lush green grass, and couples holding hands while taking a leisurely walk along the winding paths, reminding me of the simple pleasures in life that often go unnoticed in our fast-paced world, and I made a mental note to cherish these moments of stillness and connect with nature more often.",
  "The bustling city streets were filled with an endless array of sights and sounds that assaulted my senses, as honking cars weaved through traffic and people hurriedly rushed past me with their heads down, but amidst the chaos, I couldn't help but admire the vibrant energy and diversity of the city, as I caught glimpses of towering skyscrapers, quaint cafes, street performers, and colorful murals that adorned the walls of buildings, each one telling a unique story of the city's history and culture, and as I continued to explore the city's labyrinthine streets, I felt a sense of awe and inspiration that filled me with a newfound appreciation for the beauty and complexity of urban life.",
  "Stress is a common problem in modern society. It can cause physical and mental health problems, as well as negatively impact relationships and work performance. To reduce stress, it's important to identify the causes and take steps to address them. This can involve setting boundaries, prioritizing self-care, and seeking professional help if necessary. Practicing relaxation techniques such as deep breathing, yoga, or meditation can also be helpful. In addition, maintaining a healthy lifestyle with regular exercise, a balanced diet, and sufficient sleep can boost resilience and reduce the impact of stress. By taking these steps, we can improve our well-being and lead a happier, more fulfilling life.",
]
export const kanjisentence = [
  '人生には様々な挑戦があります。困難な状況に遭遇したり、自分自身の欠点を克服しなければならないことがあるかもしれません。しかし、それらの挑戦を乗り越えることで、成長し、自信をつけることができます。人生において成功するには、目標を設定し、それに向かって努力することが必要です。しかし、すべてがうまくいかないこともあるでしょう。そんなときは、諦めずに立ち上がり、再びチャレンジすることが大切です。人生は一度きりのものです。今できることを最善を尽くし、後悔のないように生きていきましょう。',
  '田中様、いつもお世話になっております。私たちのプロジェクトの進捗状況について、報告させていただきます。現在、私たちはタスクの完了に向けて努力しています。前回のミーティングで、あなたからいただいたご指摘を参考に、課題に対して改善策を検討し実施しています。進捗に関しては現在のところ予定通り進んでおり、当初の目標達成に向けて順調に進んでいると考えています。しかし、引き続き課題解決に向けて取り組んでいく必要があると考えています。今後も私たちはチーム一丸となって、プロジェクトの成功に向けて取り組んでいきます。何かご意見やご要望がございましたら、いつでもご連絡ください。以上、報告となります。よろしくお願いいたします。',
  '人々は様々な価値観を持っていますが、その中で自由や平等といった価値観は、社会の根幹を成すものと言えます。自由とは、自分の意思で行動し、思想を自由に表現することができることです。平等とは、人種や性別、宗教などに関わらず、人々が同じ権利と尊厳を持っていることを指します。自由と平等は、人々の幸福に直結する重要な要素であり、社会的にも経済的にも、持続可能な発展を実現するために必要です。私たちは、自由と平等を守り、より良い社会を築いていくために、常に努力を続けることが大切です。',
  '自然環境は、私たちが生きるうえで欠かせない存在です。しかし、現代社会においては、化石燃料の使用や大量消費などによって、自然環境が破壊され、温暖化や生物多様性の減少など、深刻な問題が生じています。このような状況下で、私たちは地球環境を守るために、積極的な行動を起こす必要があります。再生可能エネルギーの利用や、省エネルギーの普及など、個人レベルでもできることがたくさんあります。また、企業や政府も環境問題に対して責任を持ち、環境に配慮したビジネスや政策を推進することが求められています。私たちは地球環境を守り、持続可能な社会を実現するために、今こそ行動を起こす時です。',
  '親愛なる佐藤さんへ、お元気でお過ごしでしょうか。私はいつもお世話になっております。この手紙を書いている今、私は新しい挑戦を始めようとしています。少し不安もありますが、これまでの経験や学びを生かし、前向きに取り組んでいきたいと思っています。佐藤さんとの出会いは、私にとってとても大切なものでした。あなたからはたくさんのことを学び、励ましてもらったこともあります。これからも、私たちが互いに刺激し合い、成長し続ける関係を築いていけたら嬉しいです。今後も、私はあなたのご健康とご多幸を心から願っています。お会いすることができる日を楽しみにしています。敬具',
]
